//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agio.FileReader.GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agio.FileReader.GUI.Resources.GuiMessages", typeof(GuiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to read an encrypted file?.
        /// </summary>
        internal static string AskForEncryption {
            get {
                return ResourceManager.GetString("AskForEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &lt;exit&gt; to quit the program or press any key to read another file..
        /// </summary>
        internal static string AskForExit {
            get {
                return ResourceManager.GetString("AskForExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the type of the file you would like to read?.
        /// </summary>
        internal static string AskForFileTypes {
            get {
                return ResourceManager.GetString("AskForFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is your current role?.
        /// </summary>
        internal static string AskForRole {
            get {
                return ResourceManager.GetString("AskForRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use role based security?.
        /// </summary>
        internal static string AskForUsingRole {
            get {
                return ResourceManager.GetString("AskForUsingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string EmumCommandFormat {
            get {
                return ResourceManager.GetString("EmumCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the content of the file:.
        /// </summary>
        internal static string FileContent {
            get {
                return ResourceManager.GetString("FileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to close the program. Good bye!.
        /// </summary>
        internal static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Please, type &lt;Yes&gt; or &lt;No&gt;:.
        /// </summary>
        internal static string TypeYesOrNo {
            get {
                return ResourceManager.GetString("TypeYesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Agio Global .NET specialist test. 
        ///This is the BONUS part of the third exercise of the test..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
